apiVersion: v1
kind: ConfigMap
metadata:
  name: rcvr-api-config
  namespace: rcvr
data:
  dbhost: {{ .Values.dbHost }} rcvr-db-mariadb
  dbport: {{ .Values.dbPort }} "3306"
  dbname: {{ .Values.dbName }} rcvr-db
  dbuser: {{ .Values.dbUser}} RcvrDBUser

  redishost: {{ .Values.redisHost }} rcvr-session-cache-redis-master
  redisport: {{ .Values.redisPort }} "6379"

  relayhost: {{ .Values.relayHost }} rcvr-relay
  relayport: {{ .Values.relayPort }} "587"
  sender_domain: {{ .Values.senderDomain }} bsord.dev
  website_domain: {{ .Values.websiteDomain }} rcvr.bsord.dev
