apiVersion: v1
kind: ConfigMap
metadata:
  name: rcvr-api-config
  namespace: rcvr
data:
  dbhost: {{ .Values.dbHost }}
  dbport: "{{ .Values.dbPort }}"
  dbname: {{ .Values.dbName }}
  dbuser: {{ .Values.dbUser}}

  redishost: {{ .Values.redisHost }}
  redisport: "{{ .Values.redisPort }}"

  relayhost: {{ .Values.relayHost }}
  relayport: "{{ .Values.relayPort }}"
  sender_domain: {{ .Values.senderDomain }}
  website_domain: {{ .Values.websiteDomain }}
